"""
Django settings for tamm project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-please-change-this-in-production-!!!!!!")

# Application definition

INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',

    # Local apps
    'core', # Our core application
    'agents', # Our agents application
    'knowledge', # Our knowledge application
    'analytics', # Our analytics application
    'channels', # Our channels application
    'billing', # Our billing application
    'copilot', # Our copilot application
    'integrations', # Our integrations application
    'external_api', # Our external API application -- NEW
    'webchat', # Our new webchat application
    'backend.automations.apps.AutomationsConfig', # Our automations application
]

MIDDLEWARE = [
    'core.logging.RequestIdMiddleware',
    'core.metrics.MetricsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewViewMiddleware', # Disabling CSRF for API-only approach with JWT
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.WorkspaceContextMiddleware', # Our custom middleware for workspace context
    'backend.billing.middleware.RateLimitMiddleware', # Our custom middleware for workspace rate limiting
    'billing.middleware.BillingMiddleware', # Our custom middleware for billing enforcement
    'backend.external_api.middleware.ExternalApiAuthMiddleware', # Custom middleware for API Key context -- NEW
]

ROOT_URLCONF = 'tamm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tamm.wsgi.application'
ASGI_APPLICATION = 'tamm.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Supabase Postgres connection
# This will be configured more specifically in dev.py and prod.py
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'default', # Supabase DB name is typically 'postgres' or 'default'
        'USER': 'postgres', # Supabase DB user is typically 'postgres'
        'HOST': 'db.YOUR_SUPABASE_PROJECT_REF.supabase.co', # Placeholder
        'PORT': '5432',
        'PASSWORD': 'YOUR_SUPABASE_DB_PASSWORD', # Placeholder
    }
}
# Override in dev.py/prod.py with DATABASE_URL from environment variables

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom settings for JWT
SUPABASE_JWT_SECRET = os.getenv("SUPABASE_JWT_SECRET")
SUPABASE_JWT_AUD = os.getenv("SUPABASE_JWT_AUD", "authenticated") # Typically 'authenticated' for Supabase
SUPABASE_JWT_ISS = os.getenv("SUPABASE_JWT_ISS", "https://YOUR_SUPABASE_PROJECT_REF.supabase.co/auth/v1") # Placeholder

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.auth.SupabaseJWTAuthentication',
        # 'external_api.auth.WorkspaceAPIKeyAuthentication', # Removed, middleware handles API Key auth
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # Base permission
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'EXCEPTION_HANDLER': 'core.errors.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'copilot.throttles.CopilotChatThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'copilot_chat': '20/minute', # Default rate for Copilot chat endpoint
    },
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True # WARNING: This is insecure for production. Lock this down in prod.py

# Redis URL for caching and rate limiting
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")

