import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Loader2 } from "lucide-react";
import { createInstaPayPaymentRequest, InstaPayConfig } from "@/services/plans";
import { useToast } from "@/hooks/use-toast";

interface InstaPayModalProps {
  isOpen: boolean;
  onClose: () => void;
  workspaceId: string;
  planKey: string;
  amountEGP: number;
  instapayConfig: InstaPayConfig;
  onPaymentRequestCreated: (status: 'pending' | 'error') => void;
}

export default function InstaPayModal({
  isOpen,
  onClose,
  workspaceId,
  planKey,
  amountEGP,
  instapayConfig,
  onPaymentRequestCreated,
}: InstaPayModalProps) {
  const { toast } = useToast();
  const [userInstapayReference, setUserInstapayReference] = useState("");
  const [proofUrl, setProofUrl] = useState<string | null>(null); // For image/PDF upload URL
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [autoGeneratedRef, setAutoGeneratedRef] = useState<string>("");

  // This should ideally be fetched from the backend when the modal is opened
  // or passed down from PlansTab after a create_payment_request call.
  // For now, we'll generate a dummy one if not provided, but the backend generates it.
  // The 'createInstaPayPaymentRequest' call will return the *actual* generated ref.

  const handleSubmit = async () => {
    if (!userInstapayReference) {
      toast({
        title: "Missing Information",
        description: "Please enter your InstaPay transaction reference.",
        variant: "destructive",
      });
      return;
    }

    setIsSubmitting(true);
    try {
      const response = await createInstaPayPaymentRequest(
        workspaceId,
        planKey,
        userInstapayReference,
        proofUrl
      );
      toast({
        title: "Payment Request Sent",
        description: `Your InstaPay payment for ${response.amount_egp} EGP is under review. Reference: ${response.reference_code}`,
        variant: "success",
      });
      onPaymentRequestCreated('pending');
      onClose(); // Close modal on success
    } catch (error: any) {
      console.error("Failed to create InstaPay payment request:", error);
      toast({
        title: "Payment Request Failed",
        description: error.message || "Could not submit your payment request. Please try again.",
        variant: "destructive",
      });
      onPaymentRequestCreated('error');
    } finally {
      setIsSubmitting(false);
    }
  };

  // When modal opens, we might ideally fetch or generate the unique reference code from backend
  // For now, it will be returned by createInstaPayPaymentRequest
  // We can show a placeholder or let the user know it will be provided after submission.

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Pay via InstaPay</DialogTitle>
          <DialogDescription>
            Follow these instructions to complete your payment. Your plan will be
            upgraded once your payment is manually confirmed by our team.
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="space-y-2">
            <Label>Our InstaPay Details:</Label>
            <p>
              <strong>Handle:</strong> {instapayConfig.handle}
            </p>
            <p>
              <strong>Bank:</strong> {instapayConfig.bank_name}
            </p>
            {instapayConfig.account_number && (
              <p>
                <strong>Account:</strong> {instapayConfig.account_number}
              </p>
            )}
            <p>
              <strong>Amount:</strong> {amountEGP.toFixed(2)} EGP (for {planKey} plan)
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="instapay-ref">Your Unique Reference Code</Label>
            <p className="text-sm text-muted-foreground">
                When transferring, please include this code in the transaction notes/description for faster processing.
            </p>
            <Input
                id="auto-generated-ref"
                value="Will be generated upon submission" // This will be returned by the backend
                readOnly
                className="font-mono bg-gray-100 dark:bg-gray-800"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="user-instapay-ref">Your InstaPay Transaction Reference</Label>
            <Input
              id="user-instapay-ref"
              placeholder="e.g., Bank transaction ID"
              value={userInstapayReference}
              onChange={(e) => setUserInstapayReference(e.target.value)}
              required
            />
          </div>

          {/* Optional: Proof Upload Field */}
          {/* This would require an actual file upload service (e.g., Supabase Storage) */}
          {/* For now, it's just a text input for a URL */}
          <div className="space-y-2">
            <Label htmlFor="proof-url">Optional: Link to Payment Proof (Image/PDF)</Label>
            <Input
              id="proof-url"
              placeholder="e.g., Google Drive link, Imgur link"
              value={proofUrl || ""}
              onChange={(e) => setProofUrl(e.target.value)}
            />
          </div>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={onClose} disabled={isSubmitting}>
            Cancel
          </Button>
          <Button onClick={handleSubmit} disabled={isSubmitting}>
            {isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            Submit Payment
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}