// supabase/functions/_shared/types.ts

// Define the structure for connector configuration, assuming it's a JSON object
export interface ConnectorConfig {
    // Example fields, can be extended as needed for different connector types
    url?: string;
    api_key?: string;
    sheet_id?: string;
    range?: string;
    // Add other generic or specific config properties here
    [key: string]: any; // Allow arbitrary properties
}

// Define the structure for a canonical Employee Profile
export interface EmployeeProfile {
    id?: string; // UUID, will be generated by DB or provided by external_id
    workspace_id: string;
    external_id: string; // ID from the external HR system
    full_name: string;
    role?: string;
    department?: string;
    metadata?: Record<string, any>; // Arbitrary metadata from the source
}

// Define the structure for a canonical Employee Event
export interface EmployeeEvent {
    id?: string; // UUID
    workspace_id: string;
    employee_id: string; // References public.employee_profiles(id)
    event_type: string;
    payload?: Record<string, any>; // Event-specific data
    occurred_at: string; // ISO string
}

// Define the structure for a canonical Employee KPI
export interface EmployeeKpi {
    id?: string; // UUID
    workspace_id: string;
    employee_id: string; // References public.employee_profiles(id)
    kpi_key: string;
    kpi_value: number;
    period_start?: string; // YYYY-MM-DD
    period_end?: string; // YYYY-MM-DD
}

// Define the structure for a canonical Employee Complaint
export interface EmployeeComplaint {
    id?: string; // UUID
    workspace_id: string;
    employee_id: string; // References public.employee_profiles(id)
    category?: string;
    description: string;
    status?: string; // e.g., 'open', 'resolved'
}

// Define the structure for a canonical Policy Document
export interface PolicyDocument {
    id?: string; // UUID
    workspace_id: string;
    title: string;
    body: string;
    version?: string;
}
